export const WILAYAH_ACTIONS = {
    GET_PROVINSI : 'GET_PROVINSI',
    GET_KABUPATEN : 'GET_KABUPATEN',
    GET_KECAMATAN : 'GET_KECAMATAN',
    GET_KELURAHAN : 'GET_KELURAHAN',
}

export const OPTION_MENU_ACTIONS = {
    PETANI : 'PETANI',
    LAHAN : 'LAHAN',
    PANEN : 'PANEN',
    DATA_SELECTED : 'DATA_SELECTED',
    CARD : 'FOR_CARD',
}