export const WILAYAH_ACTIONS = {
    GET_PROVINSI : 'GET_PROVINSI',
    GET_KABUPATEN : 'GET_KABUPATEN',
    GET_KECAMATAN : 'GET_KECAMATAN',
    GET_KELURAHAN : 'GET_KELURAHAN',
}

export const OPTION_MENU_ACTIONS = {
    PROFILE : 'PROFILE',
    PETANI : 'PETANI',
    LAHAN : 'LAHAN',
}